/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Exercise11_10 */

#ifndef _Included_Exercise11_10
#define _Included_Exercise11_10
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
